language: minimal

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.29.2

before_install:
  # Install specific docker-compose if needed
  - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

script:
  # Build Docker images
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  # Tag images with DockerHub username + Travis build number
  - docker tag udagram-api-feed amrshams/udagram-api-feed:build-$TRAVIS_BUILD_NUMBER
  - docker tag udagram-api-user amrshams/udagram-api-user:build-$TRAVIS_BUILD_NUMBER
  - docker tag udagram-frontend amrshams/udagram-frontend:build-$TRAVIS_BUILD_NUMBER
  - docker tag reverseproxy amrshams/reverseproxy:build-$TRAVIS_BUILD_NUMBER

after_success:
  # Login to DockerHub and push images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push amrshams/udagram-api-feed:build-$TRAVIS_BUILD_NUMBER
  - docker push amrshams/udagram-api-user:build-$TRAVIS_BUILD_NUMBER
  - docker push amrshams/udagram-frontend:build-$TRAVIS_BUILD_NUMBER
  - docker push amrshams/reverseproxy:build-$TRAVIS_BUILD_NUMBER
