apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: amrshams/reverseproxy:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-config
