name: Udagram CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:latest ./udagram-frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:latest

      - name: Build & Push API User
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:latest ./udagram-api-user
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:latest

      - name: Build & Push API Feed
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:latest ./udagram-api-feed
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:latest

      - name: Build & Push Reverse Proxy
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/udagram-reverseproxy:latest ./udagram-reverseproxy
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-reverseproxy:latest
